logging:
  config: classpath:logback.xml

################### 数据库方言 ##########################
jdbc:
  dialect: MySQL
  workid: 10
################### DataSource Configuration ##########################
security:
  ignored: /**/**.js,/**/**.css,/**/**.png,/**/**.jpg,/**/**.html,/**/favicon.ico,/**/**.mp3,/**/**.gif,/**/**.mp4, /**/css/**

spring:
  devtools:
    restart:
      exclude: component/**,media/**,META-INF/**,templates/**,wechat/**,ow/**
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: utf-8
    content-type: text/html
    prefix: /templates/
    suffix: .html
    mode: HTML


  http:
    multipart:
      max-file-size: 52428800
      max-request-size: 52428800

#server:
#  port: 9080

